Added estra options. Needs testing

diff --git a/raspi-config b/raspi-config
--- a/raspi-config
+++ b/raspi-config
@@ -200,21 +200,25 @@ do_change_timezone() {
 }
 
 do_change_hostname() {
-  whiptail --msgbox "\
+  if [[ -z "$1" ]] ; then
+    whiptail --msgbox "\
 Please note: RFCs mandate that a hostname's labels \
 may contain only the ASCII letters 'a' through 'z' (case-insensitive), 
 the digits '0' through '9', and the hyphen.
 Hostname labels cannot begin or end with a hyphen. 
 No other symbols, punctuation characters, or blank spaces are permitted.\
 " 20 70 1
+    [[ $? -ne 0 ]] && return
+    NEW_HOSTNAME=$(whiptail --inputbox "Please enter a hostname" 20 60 "$CURRENT_HOSTNAME" 3>&1 1>&2 2>&3)
+  else
+    NEW_HOSTNAME=$1
+  fi
 
   CURRENT_HOSTNAME=`cat /etc/hostname | tr -d " \t\n\r"`
-  NEW_HOSTNAME=$(whiptail --inputbox "Please enter a hostname" 20 60 "$CURRENT_HOSTNAME" 3>&1 1>&2 2>&3)
-  if [ $? -eq 0 ]; then
+
     echo $NEW_HOSTNAME > /etc/hostname
-    sed -i "s/127.0.1.1.*$CURRENT_HOSTNAME/127.0.1.1\t$NEW_HOSTNAME/g" /etc/hosts
+    sed -ie "s/127.0.1.1.*$CURRENT_HOSTNAME/127.0.1.1\t$NEW_HOSTNAME/g" /etc/hosts
     ASK_TO_REBOOT=1
-  fi
 }
 
 do_memory_split() { # Memory Split
@@ -227,12 +231,15 @@ do_memory_split() { # Memory Split
     CUR_GPU_MEM=$(get_config_var gpu_mem /boot/config.txt)
     [ -z "$CUR_GPU_MEM" ] && CUR_GPU_MEM=64
     ## ask users what gpu_mem they want
-    NEW_GPU_MEM=$(whiptail --inputbox "How much memory should the GPU have?  e.g. 16/32/64/128/256" \
-      20 70 -- "$CUR_GPU_MEM" 3>&1 1>&2 2>&3)
-    if [ $? -eq 0 ]; then
-      set_config_var gpu_mem "$NEW_GPU_MEM" /boot/config.txt
-      ASK_TO_REBOOT=1
+    if [[ -s "$1" && ( $1 == 16 || $1 == 32 || $1 == 64 || $1 == 128 || $1 == 256 )  ]] ; then
+      NEW_GPU_MEM=$1
+    else
+      NEW_GPU_MEM=$(whiptail --inputbox "How much memory should the GPU have?  e.g. 16/32/64/128/256" \
+        20 70 -- "$CUR_GPU_MEM" 3>&1 1>&2 2>&3)
+        [[ $? -gt 0 ]] && return 1  # dialog failed
     fi
+    set_config_var gpu_mem "$NEW_GPU_MEM" /boot/config.txt
+    ASK_TO_REBOOT=1
   else # Old firmware so do start.elf renaming
     get_current_memory_split
     MEMSPLIT=$(whiptail --menu "Set memory split.\n$MEMSPLIT_DESCRIPTION" 20 60 10 \
@@ -270,6 +277,7 @@ set_memory_split() {
 }
 
 do_overclock() {
+  if [[ -z "$1" ||  $1 -ne "None" && $1 -ne "Modest" && $1 -ne "Medium" && $1 -ne "High" && $1 -ne "Turbo"  ]] ; then
   whiptail --msgbox "\
 Be aware that overclocking may reduce the lifetime of your
 Raspberry Pi. If overclocking at a certain level causes
@@ -284,7 +292,8 @@ See http://elinux.org/RPi_Overclocking for more information.\
     "High" "950MHz ARM, 250MHz core, 450MHz SDRAM, 6 overvolt" \
     "Turbo" "1000MHz ARM, 500MHz core, 600MHz SDRAM, 6 overvolt" \
     3>&1 1>&2 2>&3)
-  if [ $? -eq 0 ]; then
+    [ $? -ne 0 ] && return
+  fi
     case "$OVERCLOCK" in
       None)
         set_overclock None 700 250 400 0
@@ -310,7 +319,6 @@ See http://elinux.org/RPi_Overclocking for more information.\
         ;;
     esac
     ASK_TO_REBOOT=1
-  fi
 }
 
 set_overclock() {
@@ -493,20 +501,43 @@ do_finish() {
 for i in $*
 do
   case $i in
-  --memory-split)
-    OPT_MEMORY_SPLIT=GET
-    printf "Not currently supported\n"
-    exit 1
+  --hostname=*)
+    HOSTNAME=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+    do_change_hostname $HOSTNAME
+    printf "Please reboot\n"
+    exit 0
+    ;;
+  --overclock=*)
+    OVERCLOCK_MODE=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
+    do_overclock $OVERCLOCK_MODE
+    printf "Please reboot\n"
+    exit 0
     ;;
   --memory-split=*)
     OPT_MEMORY_SPLIT=`echo $i | sed 's/[-a-zA-Z0-9]*=//'`
-    printf "Not currently supported\n"
-    exit 1
+    do_memory_split $OPT_MEMORY_SPLIT
+    printf "Please reboot\n"
+    exit 0
+    ;;
+  --enable-camera)
+    INTERACTIVE=False
+    set_camera 1
+    exit 0
+    ;;
+  --disable-camera)
+    INTERACTIVE=False
+    set_camera 0
+    exit 0
     ;;
   --expand-rootfs)
     INTERACTIVE=False
     do_expand_rootfs
     printf "Please reboot\n"
+    exit 0
+    ;;
+  --help|-h)
+    INTERACTIVE=False
+    printf "Usage: sudo $(basename $0) [--hostname=<new_host_name>] | [--memory-split=<16|32|64|126|256>] | [--expand-rootfs] | [--enable-camera|--disable-camera] | [--overclock=<None|Modest|Medium|High|Turbo>]\n"
     exit 0
     ;;
   *)
